
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import logging

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def generate_graphs(results_dir="tests/results", output_dir="tests/graphs"):
    """
    Generates graphs from the metric CSV files.
    :param results_dir: Directory where the CSV files are located.
    :param output_dir: Directory to save the graph images.
    """
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Plot BLEU scores
    bleu_df = pd.read_csv(os.path.join(results_dir, "bleu_scores.csv"))
    plt.figure(figsize=(10, 6))
    sns.histplot(bleu_df['bleu_score'], kde=True)
    plt.title("BLEU Score Distribution")
    plt.xlabel("BLEU Score")
    plt.ylabel("Frequency")
    plt.savefig(os.path.join(output_dir, "bleu_scores_distribution.png"))
    plt.close()
    logging.info(f"BLEU score distribution graph saved to {os.path.join(output_dir, 'bleu_scores_distribution.png')}")

    # Plot ROUGE scores
    rouge_df = pd.read_csv(os.path.join(results_dir, "rouge_scores.csv"))
    plt.figure(figsize=(12, 7))
    melted_rouge_df = rouge_df.melt(id_vars=['reference', 'candidate'], value_vars=['rouge1', 'rouge2', 'rougeL'],
                                    var_name='Rouge Type', value_name='F-Measure')
    sns.boxplot(x='Rouge Type', y='F-Measure', data=melted_rouge_df)
    plt.title("ROUGE Score Distribution")
    plt.xlabel("ROUGE Type")
    plt.ylabel("F-Measure")
    plt.savefig(os.path.join(output_dir, "rouge_scores_distribution.png"))
    plt.close()
    logging.info(f"ROUGE score distribution graph saved to {os.path.join(output_dir, 'rouge_scores_distribution.png')}")


    # Plot BERTScore
    bert_df = pd.read_csv(os.path.join(results_dir, "bert_scores.csv"))
    plt.figure(figsize=(10, 6))
    sns.histplot(bert_df['bert_score'], kde=True)
    plt.title("BERTScore F1 Distribution")
    plt.xlabel("BERTScore F1")
    plt.ylabel("Frequency")
    plt.savefig(os.path.join(output_dir, "bert_scores_distribution.png"))
    plt.close()
    logging.info(f"BERTScore distribution graph saved to {os.path.join(output_dir, 'bert_scores_distribution.png')}")

if __name__ == '__main__':
    # To run this script, you must have the CSV files in the 'tests/results' directory.
    # This can be generated by running metrics_evaluator.py first.
    
    # Create dummy data for testing purposes
    if not os.path.exists("tests/results"):
        os.makedirs("tests/results")

    bleu_dummy = {'reference': ['test'], 'candidate': ['test'], 'bleu_score': [0.5]}
    pd.DataFrame(bleu_dummy).to_csv("tests/results/bleu_scores.csv", index=False)

    rouge_dummy = {'reference': ['test'], 'candidate': ['test'], 'rouge1': [0.5], 'rouge2': [0.4], 'rougeL': [0.5]}
    pd.DataFrame(rouge_dummy).to_csv("tests/results/rouge_scores.csv", index=False)

    bert_dummy = {'reference': ['test'], 'candidate': ['test'], 'bert_score': [0.9]}
    pd.DataFrame(bert_dummy).to_csv("tests/results/bert_scores.csv", index=False)
    
    generate_graphs()
